// ng-wizard-form/src/app/app.component.ts
import {Component, Inject} from '@angular/core'
import { FormBuilder, Validators } from '@angular/forms'
import { fields, steps } from '../consts'
import {IApiPostData, ICountryOption, IFields, IHobbies} from '../types'
import {OnInit} from "@angular/core";
import {MAT_DIALOG_DATA} from '@angular/material/dialog';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent implements OnInit {
  title = 'nd-wizard-form'
  fields = fields
  steps = steps
  currentStepIndex = 0
  apiPostData: null | IApiPostData = null
  isResultShown = false


  ngOnInit() {
    this.getCountries()
  }

  getCountries () {
    fetch("https://countriesnow.space/api/v0.1/countries/iso")
      .then(async (res) => {
        if (res.status === 200) {
          fields.country.options = (await res.json()).data;
        }
      })
      .catch((err) => {
        console.log(err);
      });
  }

  validateStep () {
    const step = this.steps[this.currentStepIndex]
    let isAllValid = true
    for (const [key, field] of Object.entries(step.fields)) {
      const result = field?.validate()
      field.isValid = result
      if (!result) isAllValid = false
    }
    step.isValid = isAllValid
  }
  onTextChange(key: 'first_name' | 'last_name' | 'driving_years', ev: Event) {
    this.fields[key].value = (ev.target as HTMLInputElement).value

    this.validateStep()
  }

  onSelect(countryOption: ICountryOption) {
    this.fields.country.value = countryOption

    this.validateStep()
  }
  onHobby(key: IHobbies, v: boolean) {
    if (v) {
      this.fields.hobbies.value.push(key)
    } else {
      const i = this.fields.hobbies.value.findIndex(val => val === key);
      this.fields.hobbies.value.splice(i, 1)
    }
    console.log(this.fields.hobbies.value)
  }
  test(ev: any) {
    console.log('!!!', ev)
  }

  updateCar() {
    this.fields.drives_car.value = !this.fields.drives_car.value
    this.fields.driving_years.value = "1";
    this.fields.driving_years.errors = [];
    this.fields.driving_years.isTouched = false
    this.steps[2].isValid = true;
  }

  postData() {
    this.isResultShown = true;
    this.apiPostData = {
      first_name: this.fields.first_name.value,
      last_name: this.fields.last_name.value,
      hobbies: this.fields.hobbies.value,
      country: typeof this.fields.country.value !== 'string' ? this.fields.country.value.Iso3 : '',
      drives_car: this.fields.drives_car.value,
      has_children: this.fields.has_children.value
    };

    if (this.apiPostData && this.fields.drives_car.value) {
      this.apiPostData.driving_years = this.fields.driving_years.value;
    }
  }

  protected readonly JSON = JSON;
}

<div
  class="w-[300px] mx-auto rounded-20 p-[20px] mt-40 shadow-md"
>
  <div [style]="{ display: currentStepIndex === 0 ? 'block' : 'none' }">
    <mat-form-field class="mt-6 w-full">
      <mat-label>First Name</mat-label>
      <input
        matInput
        placeholder="First Name"
        required
        [value]="fields.first_name.value"
        (input)="onTextChange('first_name', $event)"
        (focusout)="fields.first_name.isTouched = true"
      />
    </mat-form-field>
    <mat-error *ngFor="let error of fields.first_name.isTouched ? fields.first_name.errors : []">
      {{ error }}
    </mat-error>

    <br />
    <mat-form-field class="mt-6 w-full">
      <mat-label>Last Name</mat-label>
      <input
        matInput
        placeholder="Last name"
        required
        [value]="fields.last_name.value"
        (input)="onTextChange('last_name', $event)"
        (focusout)="fields.last_name.isTouched = true"
      />
    </mat-form-field>
    <mat-error *ngFor="let error of fields.last_name.isTouched ? fields.last_name.errors : []">
      {{ error }}
    </mat-error>
    <br />
    <mat-form-field *ngIf="!!fields.country.options" class="mt-6 w-full">
      <mat-label>Countries</mat-label>
      <mat-select required (focusout)="fields.country.isTouched = true">
        <mat-option
          (click)="onSelect(country)"
          *ngFor="let country of fields.country.options"
          [value]="country.Iso3"
        >
          {{ country.name }}
        </mat-option>
      </mat-select>
    </mat-form-field>
    <mat-error *ngFor="let error of fields.country.isTouched ? fields.country.errors : []">
      {{ error }}
    </mat-error>
  </div>

  <div [style]="{ display: currentStepIndex === 1 ? 'block' : 'none' }">
    <mat-radio-group (input)="fields.has_children.value = !fields.has_children.value">
      <mat-label class="block mt-6">Do you drive a children?</mat-label>
      <mat-radio-button [checked]="fields.has_children.value" [value]="true">Yes</mat-radio-button>
      <mat-radio-button [checked]="!fields.has_children.value" [value]="true">No</mat-radio-button>
    </mat-radio-group>
    <br />
    <mat-label class="block mt-6">Please choose your hobbies</mat-label>
    <mat-checkbox
      class="w-full"
      (change)="onHobby(hobby, $event.checked)"
      *ngFor="let hobby of fields.hobbies.options"
      >{{ hobby }}</mat-checkbox
    >
  </div>
  <!--page 3-->
  <div [style]="{ display: currentStepIndex === 2 ? 'block' : 'none' }">
    <mat-label class="block mt-6">Do you drive a car?</mat-label>
    <mat-radio-group (input)="updateCar()">
      <mat-radio-button [checked]="fields.drives_car.value" [value]="true">Yes</mat-radio-button>
      <mat-radio-button [checked]="!fields.drives_car.value" [value]="true">No</mat-radio-button>
    </mat-radio-group>

    <mat-form-field *ngIf="fields.drives_car.value" class="mt-6">
      <mat-label>Driving years</mat-label>
      <input
        type="number"
        [value]="fields.driving_years.value"
        (input)="onTextChange('driving_years', $event)"
        (focusout)="fields.driving_years.isTouched = true"
        matInput
        placeholder="12"
        required
      />
    </mat-form-field>
    <mat-error
      *ngFor="let error of fields.driving_years.isTouched ? fields.driving_years.errors : []"
    >
      {{ error }}
    </mat-error>
  </div>

  <div class="mt-6 flex justify-between align-bottom">
    <button
      mat-stroked-button
      [style]="{ display: currentStepIndex > 0 ? 'block' : 'none' }"
      (click)="currentStepIndex = currentStepIndex - 1"
    >
      Back
    </button>
    <button
      mat-stroked-button
      [style]="{ display: steps.length - 1 === currentStepIndex ? 'block' : 'none' }"
      [disabled]="!steps[steps.length - 1].isValid"
      (click)="postData()"
    >
      Submit
    </button>
    <button
      mat-stroked-button
      class="ml-auto"
      [style]="{ display: currentStepIndex < steps.length - 1 ? 'block' : 'none' }"
      [disabled]="!steps[currentStepIndex].isValid"
      (click)="currentStepIndex = currentStepIndex + 1"
    >
      next
    </button>
  </div>
</div>

// vue-wizard-form/src/App.vue
<template>
  <v-app class="pa-6">
    <v-dialog v-model="state.isResultShown" max-width="400">
      <v-card>
        <v-card-title> before JSON.stringify() </v-card-title>
        <v-card-text>
          <pre>{{ apiPostData }}</pre>
        </v-card-text>
      </v-card>
    </v-dialog>
    <v-main style="width: 300px; margin: 0 auto">
      <h2>{{ state.steps[state.currentStepIndex].title }}</h2>
      <v-card class="pa-6 mt-6 w-100" v-show="state.currentStepIndex === 0">
        <v-text-field
          label="First Name"
          :value="fds.first_name.value"
          @input="onValueChange('first_name', $event.target.value)"
          @focus.once="fds.first_name.isTouched = true"
          :error-messages="
            fds.first_name.isTouched ? fds.first_name.errors : []
          "
        ></v-text-field>
        <v-text-field
          label="Last Name"
          :value="fds.last_name.value"
          @input="onValueChange('last_name', $event.target.value)"
          @focus.once="fds.last_name.isTouched = true"
          :error-messages="fds.last_name.isTouched ? fds.last_name.errors : []"
        ></v-text-field>
        <v-select
          label="Select yor country"
          :items="fds.country.options ? fds.country.options : []"
          item-title="name"
          @focusout.once="fds.country.isTouched = true"
          :loading="!fds.country.options"
          v-model="state.fields.country.value"
          @update:model-value="onSelect"
          :error-messages="fds.country.isTouched ? fds.country.errors : []"
        >
        </v-select>
      </v-card>

      <v-card class="pa-6 mt-6 w-100" v-show="state.currentStepIndex === 1">
        <v-radio-group
          inline
          label="Hava You a children?"
          v-model="fds.has_children.value"
        >
          <v-radio
            label="Yes"
            :checked="fds.has_children.value"
            :value="true"
          ></v-radio>
          <v-radio
            label="No"
            :value="false"
            :checked="!fds.has_children.value"
          ></v-radio>
        </v-radio-group>
        <p class="v-label">Your hobbies</p>
        <v-checkbox
          hide-details
          density="compact"
          v-for="hobby in fds.hobbies.options"
          :label="hobby"
          :value="hobby"
          :key="hobby"
          v-model="fds.hobbies.value"
        />
      </v-card>

      <v-card
        class="pa-6 mt-6"
        style="width: 100%"
        v-show="state.currentStepIndex === 2"
      >
        <v-radio-group
          @update:model-value="updateCar"
          inline
          label="Do u drive a car?"
          v-model="fds.drives_car.value"
        >
          <v-radio
            label="Yes"
            :checked="fds.drives_car.value"
            :value="true"
          ></v-radio>
          <v-radio
            label="No"
            :value="false"
            :checked="!fds.drives_car.value"
          ></v-radio>
        </v-radio-group>

        <v-text-field
          v-show="fds.drives_car.value"
          @input="onValueChange('driving_years', $event.target.value)"
          @focus.once="fds.driving_years.isTouched = true"
          :value="fds.driving_years.value"
          :error-messages="
            fds.driving_years.isTouched ? fds.driving_years.errors : []
          "
          single-line
          type="number"
        />
      </v-card>

      <div class="pt-6 d-flex justify-space-between">
        <v-btn
          v-show="state.currentStepIndex > 0"
          @click="state.currentStepIndex--"
        >
          Back
        </v-btn>
        <v-btn
          v-show="state.steps.length - 1 === state.currentStepIndex"
          :disabled="!state.steps[state.steps.length - 1].isValid"
          @click="postData"
        >
          Submit
        </v-btn>
        <v-btn
          class="ml-auto"
          v-show="state.currentStepIndex < state.steps.length - 1"
          :disabled="!state.steps[state.currentStepIndex].isValid"
          @click="state.currentStepIndex++"
        >
          next
        </v-btn>
      </div>
    </v-main>
  </v-app>
</template>

<script lang="ts" setup>
import { reactive, ref } from "vue";
import { IFields, ICountryOption } from "@/types";
import { fields, steps } from "@/consts";

const state = reactive({
  isResultShown: false,
  fields,
  steps,
  currentStepIndex: 0,
});
const apiPostData = ref<any>(null);
const fds = state.fields;

fetch("https://countriesnow.space/api/v0.1/countries/iso")
  .then(async (res) => {
    if (res.status === 200) {
      fds.country.options = (await res.json()).data;
    }
  })
  .catch((err) => {
    console.log(err);
  });

function onValueChange(key: keyof IFields, v: IFields[typeof key]["value"]) {
  const step = state.steps[state.currentStepIndex];
  let isAllValid = true;

  fds[key].value = v;

  for (const [_key, field] of Object.entries(step.fields)) {
    const result = field.validate();
    field.isValid = result;
    if (!result) isAllValid = false;
  }

  step.isValid = isAllValid;
}

function onSelect(v: string) {
  const item = fds.country.options?.find(
    (val) => val.name === v
  ) as ICountryOption;

  onValueChange("country", item);
}
function updateCar(ev: boolean) {
  fds.driving_years.value = "1";
  fds.driving_years.errors = [];
  state.steps[2].isValid = true;
  console.log(fds.drives_car.value, ev);
}

function postData() {
  state.isResultShown = true;
  apiPostData.value = {
    first_name: fields.first_name.value,
    last_name: fields.last_name.value,
    hobbies: fields.hobbies.value,
    drives_car: fields.drives_car.value,
  };
  if (typeof fields.country.value !== "string") {
    apiPostData.value.country = fields.country.value.Iso3;
  }
  if (fields.drives_car.value) {
    apiPostData.value.driving_years = Number(fields.driving_years.value);
  }
}
</script>
